USELESS_WORDS = ["unk"]
NORMALIZATION_RULES = {
    's': '',
    'es': '',
    'ed': '',
    'ing': '',
    'ies': 'y',
    'ied': 'y',
    'er': '',
    'est': '',
    'ful': '',
    'ment': '',
    'ness': '',
    'able': '',
    'ible': '',
    'al': '',
    'ial': '',
    'ical': '',
    'y': '',
    'ify': '',
    'ize': '',
    'ise': '',
    'ship': '',
    'ward': '',
    'wise': '',
}
STOP_WORDS = [
"wasn't", 'himself', 'so', 'on', "couldn't", 'me', 'up', 'shouldn', 'your', 'while',
"mightn't", 'above', 'the', 'further', 'does', 'd', 'it', 'his', 'hasn', 'those', 'haven', 'their',
'what', 'at', 'doing', 'isn', 'few', 'of', 'when', 'now', 'or', 'itself', 'very', "needn't", "haven't",
'after', 'can', 'was', 'as', 'ain', 'did', 'whom', 'she', 'from', 'ourselves', 'how', 't', "you've", 'below',
'who', 'only', 'shan', "shouldn't", 'more', 'needn', 'been', 'just', 'an', 'with', 'didn', 'for', 'm', "wouldn't",
'them', 'once', 'll', 'but', 'against', 'this', 've', 'ma', 'its', "you're", 'will', 'between', 'herself', 'yours',
'were', "doesn't", 'too', 'are', 'if', 'to', 'these', 'ours', "it's", 'won', 'both', 'mightn', "that'll", 'is',
'and', 'there', 'here', 'am', 'hadn', 'our', 'mustn', 'because', 'again', 'until', 'hers', 'before', 'about', 
'wouldn', 'him', 'over', 'we', 'during', "you'll", 'having', 'each', 'wasn', "hasn't", 'under', 'out', "should've",
"mustn't", 'most', 'by', 'have', 're', 'doesn', 'nor', 'they', 'own', 'themselves', 'no', 'my', 's', 'you', 'i', 'all',
"won't", "didn't", "isn't", 'a', 'don', 'where', 'than', "shan't", "she's", 'into', 'her', 'weren', 'aren', 'being',
'yourselves', 'not', 'any', 'had', "weren't", 'in', 'other', 'some', 'he', "don't", "aren't", 'why', 'which', 'y',
'couldn', 'down', 'do', 'through', 'off', 'then', 'such', 'o', "hadn't", 'should', 'same', 'myself', 'that', 'has',
'theirs', 'be', 'yourself', "you'd"
]